### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by b1n-ch1kn** [QUT-Motorsport/QUTMS_Driverless#185]
Hardware:
- [x] Get EBS integrated into brake system
   - [x] Buy copper washers from Kedron
   - [x] Bleed brake lines
- [x] Mount computer boxes (#173)
   - [x] Design and review
   - [x] Send mounting plate for manufacture
   - [x] Send new 3D printed stands for flexy print
   - [x] Mount
- [x] Install wiring harness (dependent on above) (#91)
   - [x] Manufacture driverless control panel + key cover
   - [ ] Install components into control panel + cover (#183, #184)
   - [x] Wire box internals
   - [x] Grommets through boxes??
   - [x] Full harness with final routing
   - [x] Run wires for ASSI lights and EBS dash light (coming later)
- [x] ASSI Light (#68)
   - [x] Manufacture and assemble
   - [x] Design mounts/covers
   - [x] Wiring
- [x] EBS dash light (#80)
   - [x] Drill hole in dash
   - [x] Insert LED
   - [ ] Label
   - [ ] Wiring

Software:
- [x] (Operational) Integrate driverless state machine (#105)
- [ ] (Operational) Fix Velodyne crashing CAN driver (#187)
- [ ] (Operational) Interpret wheel speed data for car velocity (#188)
- [x] (Operational) Output torque correctly (-100% to 100%) (#191)
- [x] (Operational) Autonomous System Supervisor node (#189)
- [x] (Comp) Lights and siren control (#68)
- [ ] (Comp) LiDAR de-noising + optimising (#108)(#170)
- [ ] (Comp) Wheel odometry into SBG (#188)
- [x] (Comp) More robust reactive control
- [ ] (Comp) Datalogger CAN driver and database file (#72)
- [ ] Robust mapping for noisy odometry
- [ ] Implement loop closure for mapping
- [ ] Implement full path planning algorithm
- [ ] Less cooked path following
